In [2]:
import pandas as pd

In [3]:
import numpy as ny

In [4]:
from pandas import ExcelWriter
from pandas import ExcelFile


data = pd.read_excel('HospitalDatabase.xlsx')
Patient_data = pd.read_excel('HospitalDatabase.xlsx',sheet_name='Patients')
EDvisit_data = pd.read_excel('HospitalDatabase.xlsx',sheet_name='EDVisits')
Ambulatory_data = pd.read_excel('HospitalDatabase.xlsx',sheet_name='AmbulatoryVisits')
Readmission_data = pd.read_excel('HospitalDatabase.xlsx',sheet_name='ReAdmissionRegistry')
Discharges_data = pd.read_excel('HospitalDatabase.xlsx',sheet_name='Discharges')
Provider_data = pd.read_excel('HospitalDatabase.xlsx',sheet_name='Providers')
Edunique_data = pd.read_excel('HospitalDatabase.xlsx',sheet_name='EDUnique')
Patient_data


PatientID FirstName  LastName             DateOfBirth Gender  \
0            1     Lanni       Sue 1960-01-01 00:00:00.000   Male   
1            2       Far     Myers 1985-11-15 02:08:42.090   Male   
2            3   Devlin    Michael 1976-04-15 02:52:09.762   Male   
3            4   Carmine     Texas 1968-10-15 03:32:13.635   Male   
4            5     Tann       Bama 1962-05-01 19:12:58.950   Male   
..         ...       ...       ...                     ...    ...   
940        941       Wat   Fideler 1986-05-26 00:01:19.761   Male   
941        942    Wandie  Baythrop 1970-06-10 21:41:03.814   Male   
942        943   Diahann   Smeeton 1983-01-08 21:49:27.884   Male   
943        944  Panchito   Sharple 1963-06-05 07:57:05.569   Male   
944        945     Walsh    Calvie 1972-08-06 03:40:03.454   Male   

                       Race Language  
0                     White  English  
1                     White  English  
2                     White  English  
3                     White  English  
4                     White  English  
..                      ...      ...  
940  Black/African-American  English  
941  Black/African-American  English  
942  Black/African-American  English  
943  Black/African-American  English  
944  Black/African-American  English  

[945 rows x 7 columns]

In [40]:
#Q:1:  Delete the  "Gender" column in "Patients" DataFrame

Patient_data = pd.read_excel('HospitalDatabase.xlsx',sheet_name='Patients')

df = pd.DataFrame(Patient_data)
# Patient_data.head()

df.drop(df.columns[4], axis=1, inplace=True)

df

PatientID FirstName  LastName             DateOfBirth  \
0            1     Lanni       Sue 1960-01-01 00:00:00.000   
1            2       Far     Myers 1985-11-15 02:08:42.090   
2            3   Devlin    Michael 1976-04-15 02:52:09.762   
3            4   Carmine     Texas 1968-10-15 03:32:13.635   
4            5     Tann       Bama 1962-05-01 19:12:58.950   
..         ...       ...       ...                     ...   
940        941       Wat   Fideler 1986-05-26 00:01:19.761   
941        942    Wandie  Baythrop 1970-06-10 21:41:03.814   
942        943   Diahann   Smeeton 1983-01-08 21:49:27.884   
943        944  Panchito   Sharple 1963-06-05 07:57:05.569   
944        945     Walsh    Calvie 1972-08-06 03:40:03.454   

                       Race Language  
0                     White  English  
1                     White  English  
2                     White  English  
3                     White  English  
4                     White  English  
..                      ...      ...  
940  Black/African-American  English  
941  Black/African-American  English  
942  Black/African-American  English  
943  Black/African-American  English  
944  Black/African-American  English  

[945 rows x 6 columns]

In [29]:
# Q2: Display Patientid, FIrstname ,Lastname And provider Details (Join three Dataframes )
Patient_data = pd.read_excel('HospitalDatabase.xlsx',sheet_name='Patients',usecols='A,B,C')
Ambulatory_data = pd.read_excel('HospitalDatabase.xlsx',sheet_name='AmbulatoryVisits',usecols='B,C')
Provider_data = pd.read_excel('HospitalDatabase.xlsx',sheet_name='Providers',usecols='A,B,C')


Patient_data.merge(Ambulatory_data,left_on='PatientID', right_on='PatientMRN').merge(Provider_data,left_on='ProviderID',right_on='ProviderID')


PatientID  FirstName     LastName  PatientMRN  ProviderID  \
0            4    Carmine        Texas           4           1   
1           39       Dave    D'Ambrogi          39           1   
2           42       Kent   Priestnall          42           1   
3           62      Holly       Durant          62           1   
4           88     Myrtia       Revett          88           1   
..         ...        ...          ...         ...         ...   
945        888  Rosemonde   Eschalotte         888          15   
946        890   Philippa    MacTeague         890          15   
947        897    Barrows     Coupland         897          15   
948        898     Melina     Siseland         898          15   
949        916     Kaylil      Baldack         916          15   

        ProviderName ProviderSpecialty  
0          Sally Sue        Pediatrics  
1          Sally Sue        Pediatrics  
2          Sally Sue        Pediatrics  
3          Sally Sue        Pediatrics  
4          Sally Sue        Pediatrics  
..               ...               ...  
945  Christian Saint           Surgery  
946  Christian Saint           Surgery  
947  Christian Saint           Surgery  
948  Christian Saint           Surgery  
949  Christian Saint           Surgery  

[950 rows x 7 columns]

In [45]:
#Q:3  Finding union, intersect,differnce and Symmerterical difference of two arrays

a =ny.array([1,2,3,4,5,6])
print(a)

b =ny.array([5,6,7,8,9,10])
print(b)

c = a.reshape(3,2)
print(c)


d = b.reshape(3,2)
print(d)


abunion = ny.union1d(a,b)

abintersect = ny.intersect1d(a, b, assume_unique=True)

ab_difference = ny.setdiff1d(a, b, assume_unique=True)
ba_difference = ny.setdiff1d(b, a, assume_unique=True)
absymdiff = ny.setxor1d(a, b, assume_unique=True)



print("Union of a and b", abunion)
print("intersect of a and b",abintersect )
print("difference of a and b",ab_difference )
print("difference of b and b",ba_difference)
print("Symmetricdifference of a and b",absymdiff)

[1 2 3 4 5 6]
[ 5  6  7  8  9 10]
[[1 2]
 [3 4]
 [5 6]]
[[ 5  6]
 [ 7  8]
 [ 9 10]]
Union of a and b [ 1  2  3  4  5  6  7  8  9 10]
intersect of a and b [5 6]
difference of a and b [1 2 3 4]
difference of b and b [ 7  8  9 10]
Symmetricdifference of a and b [ 1  2  3  4  7  8  9 10]


In [35]:
#Q4:   np.arange(1,10).reshape(3,3): 3 by 3 array addtion and subtraction
a = ny.arange(1,10)
print(a)
b= a.reshape(3,3)
print(b)


c = ny.array([[2, 2, 2], [2, 2, 2],[2,2,2]])

for x in c:
    print(x)

arr_add = b + c
arr_sub = b - c

print("Array Addition of b and C:",)
print(arr_add)
print("Array Subtraction of b and C:",)
print(arr_sub)



[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 2 2]
[2 2 2]
[2 2 2]
Array Addition of b and C:
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Array Subtraction of b and C:
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


In [55]:
#Q5: check whether a string starts with specified characters.

string = "Numpy Ninja - Python Hackathan"
print( "string start with  Num: ")
print(string.startswith("Num"))
print("string Start with 'python':")
print(string.startswith("pyt"))

string start with  Num: 
True
string Start with 'python':
False


In [64]:
#Q6: convert FirstName into Upper and Lower cases in DataFrame
Patient_data = pd.read_excel('HospitalDatabase.xlsx',sheet_name='Patients',usecols='B')

df = pd.DataFrame(Patient_data)
df1 = pd.DataFrame(Patient_data)
print("Upper cases in First Name")
df['FirstName'] = list(map(lambda x: x.upper(), df['FirstName']))
print(df)
print("Lower cases in FirstName")
df1['FirstName'] = list(map(lambda x: x.lower(), df['FirstName']))
print(df1)

Upper cases in First Name
    FirstName
0       LANNI
1         FAR
2     DEVLIN 
3     CARMINE
4       TANN 
..        ...
940       WAT
941    WANDIE
942   DIAHANN
943  PANCHITO
944     WALSH

[945 rows x 1 columns]
Lower cases in FirstName
    FirstName
0       lanni
1         far
2     devlin 
3     carmine
4       tann 
..        ...
940       wat
941    wandie
942   diahann
943  panchito
944     walsh

[945 rows x 1 columns]


In [ ]:
#Q7:
